#!/bin/bash

echo -e "Checking branch name..."
branchName=$(git branch | grep '*' | sed 's/* //')

if [ $branchName == 'main' ]
then
  echo -e "🚫 Commit directly to main branch is not allowed, please create your own branch and send a pull request" && exit 1
fi

if [ $branchName == 'develop' ]
then
  echo -e "🚫 Cannot push to remote develop branch, please create your own branch and send a pull request" && exit 1
fi

if [[ $branchName = *[![:ascii:]]* ]]
then
  echo -e "🚫 Branch name should not have any ascii, please rename your branch name" && exit 1
fi

echo -e ">> Finished checking branch name." && exit 0
