#!/bin/bash

echo -e "Checking branch name..."

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(main|develop)"

if [[ $1 != "origin" && $2 != *"$BRANCH"* ]]
then
  echo -e "🚫 You must use (git push origin $BRANCH)\n" && exit 1
fi

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and send a pull request" && exit 1
fi

echo -e ">> Finished checking branch name." && exit 0
